export const modalStyle = {
    position: 'absolute' as 'absolute',
    padding:"1em",
    display:'flex',
    flexDirection:'column',
    textAlign:"center",
    justifyContent: 'space-between',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 400,
    backgroundColor: 'white',
    border: '2px solid #000',
    boxShadow: 24,
    p: 4,
};